<?php

// -----------------------------------------
// semplice
// admin/atts/customize/advanced.php
// -----------------------------------------

$advanced = array(
	'text' => array(
		'title'	 		=> 'Text Colors',
		'description' 	=> 'Define the basic text colors for your paragraphs.',
		'text_color' => array(
			'title'			=> 'Text Color',
			'size'			=> 'span1',
			'data-input-type'	=> 'color',
			'default'		=> '#000000',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-picker'	=> 'advanced',
		),
		'link_color' => array(
			'title'			=> 'Link Color',
			'size'			=> 'span1',
			'data-input-type'	=> 'color',
			'default'		=> '#1573dd',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-picker'	=> 'advanced',
		),
		'mouseover_color' => array(
			'title'			=> 'Hover Color',
			'size'			=> 'span1',
			'data-input-type'	=> 'color',
			'default'		=> '#000000',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-picker'	=> 'advanced',
		),
	),
	'progress-bar' => array(
		'title'	 		=> 'Loader Bar Color',
		'description' 	=> 'Define the color of your \'Loader Bar\'',
		'progress_bar' => array(
			'title'			=> 'Progress Bar Color',
			'hide-title'	=> true,
			'size'			=> 'span2',
			'data-input-type'	=> 'color',
			'default'		=> 'transparent',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-picker'	=> 'advanced',
		),
	),
	'back-to-top' => array(
		'title'	 		=> 'Back To Top Arrow Color',
		'description' 	=> 'Define the color of your \'Back to top\' arrow.',
		'top_arrow_color' => array(
			'title'			=> 'Back To Top Arrow Color',
			'hide-title'	=> true,
			'size'			=> 'span2',
			'data-input-type'	=> 'color',
			'default'		=> 'transparent',
			'class'			=> 'color-picker admin-listen-handler',
			'data-handler'  => 'colorPicker',
			'data-picker'	=> 'advanced',
		),
	),
	'global-footer' => array(
		'title'	 		=> 'Global Footer',
		'description' 	=> 'Define your global footer here. To define an individual footer for a page or project please do this in the post settings.<br /><br />Note: If your footer is not listed here, please make sure it\'s published already.',
		'global_footer' => array(
			'title'				 => 'Global Footer',
			'hide-title'		 => true,
			'size'				 => 'span2',
			'data-input-type'    => 'select-box',
			'class'			  	 => 'admin-listen-handler',
			'data-handler'       => 'advanced',
			'default'			 => '1',
			'data-settings-type' => 'general',
			'select-box-values' => semplice_get_post_dropdown('footer'),
		),
	),
	'password_protected' => array(
		'title' => 'Password Protected Content',
		'description' 	=> 'Choose the theme for your password protected page or project.<br /><br />To further customize the protected screen colors, you can use this: <a href="https://pastebin.com/fdjRYLMg" target="_blank">css snippet</a>. Add it to the Global Custom CSS option below, which will apply it to all protected content, or individually within the Custom CSS option for specific pages or projects.',
		'password_form_theme' => array(
			'data-input-type' 	=> 'switch',
			'switch-type'		=> 'twoway',
			'title'				=> 'Password protected',
			'hide-title'		=> true,
			'size'				=> 'span4',
			'class'				=> 'admin-listen-handler',
			'data-handler'  	=> 'advanced',
			'default' 	 		=> 'bright',
			'switch-values' => array(
				'bright'	 => 'Bright',
				'dark' 	 => 'Dark',
			),
		),
	),
	'motion-tab' => array(
		'title'	 		=> 'Unlock Editor Motion Options',
		'description' 	=> 'Enable this option to activate the "Motion" feature. After enabling you will find motions in your edit popup in the content editor. See how it works <a href="https://vimeo.com/223057583/fe7b10f522" target="_blank">here</a>.',
		'motion_tab' => array(
			'data-input-type' 	=> 'switch',
			'switch-type'		=> 'twoway',
			'title'				=> 'Motion Options',
			'hide-title'		=> true,
			'size'				=> 'span4',
			'class'				=> 'admin-listen-handler',
			'data-handler'  	=> 'advanced',
			'default' 	 		=> 'disabled',
			'switch-values' => array(
				'disabled'	 => 'Disabled',
				'enabled' 	 => 'Enabled',
			),
		),
	),
	'custom-css' => array(
		'title' 		=> 'Custom CSS',
		'description' 	=> 'Choose the custom css you want to edit from the select box and hit \'Edit Custom CSS\'',
		'custom_css_switch' => array(
			'title'				=> 'Custom CSS Switch',
			'hide-title'		=> true,
			'size'				=> 'span2',
			'data-input-type'	=> 'select-box',
			'class'				=> 'admin-listen-handler',
			'data-handler'  	=> 'advanced',
			'select-box-values' => array(
				'global'		=> 'Global',
				'xl'			=> 'Desktop Wide',
				'lg'			=> 'Desktop',
				'md'			=> 'Tablet Wide',
				'sm'			=> 'Tablet Portrait',
				'xs'			=> 'Mobile',
			),
		),
		'custom_css' 	=> array(
			'title'				=> 'Edit CSS Code',
			'hide-title'		=> true,
			'size'				=> 'span2',
			'help'				=> '',
			'data-input-type'	=> 'codemirror',
			'placeholder'		=> '',
			'default'			=> '',
			'button-title'		=> 'Edit Custom css',
			'class'				=> 'semplice-button codemirror white-button admin-click-handler',
			'data-handler'		=> 'codemirror',
		),
	),
	'custom-js' => array(
		'title' 		=> 'Custom Javascript',
		'description' 	=> 'This custom javascript gets applied globally to all pages and projects.<br /><br />Note: Please start right away with your javascript code without using any html tags like (< script >).<br /><br />Example: alert("Hello World");',
		'custom_js' 	=> array(
			'title'				=> 'Edit CSS Code',
			'hide-title'		=> true,
			'size'				=> 'span2',
			'offset'			=> 'offset2',
			'help'				=> '',
			'data-input-type'	=> 'codemirror',
			'placeholder'		=> '',
			'default'			=> '',
			'button-title'		=> 'Edit Javascript',
			'class'				=> 'semplice-button codemirror white-button admin-click-handler',
			'data-handler'		=> 'codemirror',
		),
	),
);